project_id = "irauraejdmkjkrbdudra"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.send-crm-email]
verify_jwt = false

[functions.generate-email-draft]
verify_jwt = false