-- Sequenza per i codici ordine
CREATE SEQUENCE IF NOT EXISTS public.order_code_seq START 1000;

-- Funzione che genera il codice ordine
CREATE OR REPLACE FUNCTION public.generate_order_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.order_code IS NULL OR NEW.order_code = '' THEN
    NEW.order_code := 'ORD-' || TO_CHAR(NOW(), 'YYYY') || '-' || LPAD(nextval('order_code_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger sulla tabella orders
DROP TRIGGER IF EXISTS set_order_code ON public.orders;
CREATE TRIGGER set_order_code
  BEFORE INSERT ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.generate_order_code();

-- Fix retroattivo: aggiorna gli ordini esistenti senza codice
UPDATE public.orders
SET order_code = 'ORD-' || TO_CHAR(created_at, 'YYYY') || '-' || LPAD(nextval('order_code_seq')::TEXT, 5, '0')
WHERE order_code IS NULL OR order_code = '';

-- Update RPC to recalculate subtotals server-side
CREATE OR REPLACE FUNCTION public.create_order_with_items(
  p_client_id UUID,
  p_status TEXT DEFAULT 'draft',
  p_notes TEXT DEFAULT NULL,
  p_payment_terms TEXT DEFAULT NULL,
  p_order_type TEXT DEFAULT NULL,
  p_items JSONB DEFAULT '[]'::JSONB,
  p_internal_notes TEXT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_order_id UUID;
  v_order_code TEXT;
  v_total NUMERIC := 0;
  v_item JSONB;
  v_unit_price NUMERIC;
  v_quantity INTEGER;
  v_subtotal NUMERIC;
  v_product_id UUID;
  v_discount_pct NUMERIC;
BEGIN
  -- Validate status
  IF p_status NOT IN ('draft', 'submitted', 'confirmed', 'processing', 'ready_to_ship', 'shipped', 'delivered', 'cancelled', 'returned') THEN
    RAISE EXCEPTION 'Invalid order status: %', p_status;
  END IF;

  -- Calculate total by recalculating subtotals server-side
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_unit_price := (v_item->>'unit_price')::NUMERIC;
    v_quantity   := (v_item->>'quantity')::INTEGER;

    IF v_unit_price IS NULL OR v_unit_price <= 0 THEN
      RAISE EXCEPTION 'Invalid unit_price for product %', v_item->>'product_id';
    END IF;
    IF v_quantity IS NULL OR v_quantity <= 0 THEN
      RAISE EXCEPTION 'Invalid quantity for product %', v_item->>'product_id';
    END IF;

    v_subtotal := ROUND(v_unit_price * v_quantity, 2);
    v_total    := v_total + v_subtotal;
  END LOOP;

  -- Create order (order_code generated by trigger)
  INSERT INTO public.orders (
    client_id, status, notes, internal_notes, payment_terms, order_type,
    total_amount, created_at, updated_at
  )
  VALUES (
    p_client_id, p_status, p_notes, p_internal_notes, p_payment_terms, p_order_type,
    v_total, NOW(), NOW()
  )
  RETURNING id, order_code INTO v_order_id, v_order_code;

  -- Insert items with server-recalculated subtotals
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id  := (v_item->>'product_id')::UUID;
    v_unit_price  := (v_item->>'unit_price')::NUMERIC;
    v_quantity    := (v_item->>'quantity')::INTEGER;
    v_discount_pct := COALESCE((v_item->>'discount_pct')::NUMERIC, 0);
    v_subtotal    := ROUND(v_unit_price * v_quantity, 2);

    INSERT INTO public.order_items (
      order_id, product_id, quantity, unit_price, discount_pct, subtotal
    )
    VALUES (v_order_id, v_product_id, v_quantity, v_unit_price, v_discount_pct, v_subtotal);
  END LOOP;

  -- Log event
  INSERT INTO public.order_events (order_id, event_type, title, created_at)
  VALUES (v_order_id, 'status_change', 'Order created with status: ' || p_status, NOW());

  RETURN jsonb_build_object(
    'order_id', v_order_id,
    'order_code', v_order_code,
    'total', v_total
  );

EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;