CREATE OR REPLACE FUNCTION public.create_order_with_items(
  p_client_id UUID,
  p_status TEXT DEFAULT 'draft',
  p_notes TEXT DEFAULT NULL,
  p_payment_terms TEXT DEFAULT NULL,
  p_order_type TEXT DEFAULT NULL,
  p_items JSONB DEFAULT '[]'::jsonb
) RETURNS JSONB AS $$
DECLARE
  v_order_id UUID;
  v_order_code TEXT;
  v_total NUMERIC := 0;
  v_item JSONB;
BEGIN
  -- Calculate total
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_total := v_total + COALESCE((v_item->>'subtotal')::numeric, 0);
  END LOOP;

  -- Insert order (order_code is generated by trigger)
  INSERT INTO public.orders (client_id, status, total_amount, notes, payment_terms, payment_status, order_type)
  VALUES (p_client_id, p_status, v_total, p_notes, p_payment_terms, 'unpaid', p_order_type)
  RETURNING id, order_code INTO v_order_id, v_order_code;

  -- Insert all items
  INSERT INTO public.order_items (order_id, product_id, quantity, unit_price, discount_pct, subtotal)
  SELECT
    v_order_id,
    (item->>'product_id')::uuid,
    COALESCE((item->>'quantity')::integer, 1),
    (item->>'unit_price')::numeric,
    COALESCE((item->>'discount_pct')::numeric, 0),
    COALESCE((item->>'subtotal')::numeric, 0)
  FROM jsonb_array_elements(p_items) AS item;

  RETURN jsonb_build_object('id', v_order_id, 'order_code', v_order_code);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;