
-- Update Flipper Max with full specs from website
UPDATE public.product_details SET
  description = 'The EasySea Flipper™ Max is a foldable winch handle engineered for superior performance on larger boats. With its extended lever and innovative folding mechanism, it enhances maneuvering efficiency while ensuring convenience and durability. A longer lever reduces the effort required for tough maneuvers. Compatible with various winch sizes and equipped with a universal star attachment.',
  features = '["Foldable: compact design that never gets in the way while manoeuvring", "Always on the winch: ready to use, never gets lost overboard", "Ultra-resistant: proven durability, trusted by sailors since 2019", "Extended leverage: longer lever (254mm / 10in) reduces effort required", "Universal fit: compatible with various winch sizes", "Robust construction: CNC-milled 6082 anticorodal aluminum with 316L stainless steel joints"]'::jsonb,
  specifications = '{"Recommended boat length": "10 to 18 meters (33ft to 59ft)", "Recommended winch sizes": "45, 46, 50, 55, 65, 70", "Main material": "Aluminum 6082", "Treatment": "Hard anodization matte black", "Pins material": "Stainless steel inox 316L", "Dimensions closed": "290mm (7.48 inches)", "Dimensions open": "254mm (10 inches)", "Weight": "722 gr (1.59 lb)", "Max working load": "400 Kg (881 lb)", "Breaking load": "800 Kg (1763 lb)", "Warranty": "4 years"}'::jsonb,
  gallery_images = '["https://easysea.org/cdn/shop/files/GRAFICA-FLIPPER_MAX-01.webp?v=1764792536&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-FLIPPER_MAX-02.webp?v=1764792536&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-FLIPPER_MAX-03.webp?v=1764792536&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-FLIPPER_MAX-04.webp?v=1764792536&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-FLIPPER_MAX-06.webp?v=1764792536&width=4500"]'::jsonb
WHERE product_family = 'flipper-max';

-- Update Olli Ring with full specs
UPDATE public.product_details SET
  description = 'The Olli™ Low Friction Ring is an innovative anti-shock ring that protects your boat from impacts while providing ultra-low friction for smooth line handling. Thanks to its rubber edge, Olli™ absorbs impacts, protecting both equipment and the boat. The innovative design prevents scratches and damage, minimizes noise caused by impacts or vibrations. Available in 5 sizes (XS to XL).',
  features = '["Anti-Shock Protection: rubber edge absorbs impacts, protecting equipment and boat", "Anti-Scratch Protection: prevents scratches and damage to surfaces", "Anti-Noise System: rubber edge minimizes noise from impacts or vibrations", "Ultra-low friction for smooth line handling", "Aerospace-grade materials for durability", "Available in 5 sizes: XS, S, M, L, XL", "30-day money-back guarantee"]'::jsonb,
  specifications = '{"Main material": "Aluminum 6082", "Treatment": "Hard anodization", "Edge material": "Anti-shock rubber", "Available sizes": "XS | S | M | L | XL", "Surface": "Ultra-low friction", "Manufacturing": "CNC machining", "Warranty": "4 years"}'::jsonb,
  technical_sheet_url = 'https://cdn.shopify.com/s/files/1/0244/3188/6432/files/Technical_Sheet_Olli_alluminio.pdf?v=1742566286',
  gallery_images = '["https://easysea.org/cdn/shop/files/GRAFICA-OLLI-LOW-FRICTION-RING-01.png?v=1768850397&width=1620", "https://easysea.org/cdn/shop/files/GRAFICA-OLLI-LOW-FRICTION-RING-02.webp?v=1768850397&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-OLLI-LOW-FRICTION-RING-03.webp?v=1768850397&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-OLLI-LOW-FRICTION-RING-04.webp?v=1768850397&width=4500", "https://easysea.org/cdn/shop/files/GRAFICA-OLLI-LOW-FRICTION-RING-06.webp?v=1768850397&width=4500"]'::jsonb
WHERE product_family = 'olli-ring';

-- Update Way2 with full specs
UPDATE public.product_details SET
  description = 'WAY2 is the new inflatable gangway by Easysea, designed to offer the perfect balance between functionality, safety, and freedom of use. Compact when folded (only 0.03 m³, less than a small cabin suitcase), it transforms in seconds into a rigid, stable, walkable gangway. Built with high-pressure drop-stitch technology, featuring anti-slip surface, stainless steel hooks, ergonomic handles, and a high-pressure valve. WAY2 is more than a gangway — it''s a modular, multifunctional solution. Use it as a SUP, floating mat, or work platform.',
  features = '["Versatile: much more than just a gangway — use as SUP, floating mat, or work platform", "Lightweight: lift it with one hand", "Stowable: only 0.03 m³ when folded, fits in smallest lockers", "Dropstitch Technology: high-density internal structure for stiffness comparable to solid board", "Double-Layer PVC: marine-grade, heat-welded, UV and saltwater resistant", "EasyGrip™ EVA Surface: hexagonal anti-slip pattern for superior grip", "No maintenance required, doesn''t corrode"]'::jsonb,
  specifications = '{"Dimensions": "200 x 50 x 15 cm", "Folded volume": "0.03 m³", "Construction": "High-pressure drop-stitch technology", "Surface": "EasyGrip™ EVA hexagonal anti-slip", "Outer layer": "Double-Layer PVC, heat-welded", "Valve": "High-Pressure technical polymer + stainless steel (up to 20 PSI)", "Seams": "Heat-welded, monolithic, fully waterproof", "Attachments": "Steel hooks & ergonomic handles", "Use cases": "Gangway, SUP, floating mat, work platform", "Warranty": "4 years"}'::jsonb
WHERE product_family = 'way2';

-- Update Spira with full specs
UPDATE public.product_details SET
  description = 'Spira is a guardrail cover designed to provide safety, comfort, and fast installation without tools. Its spiral-cut foam core wraps around the lifeline effortlessly, preventing the stainless-steel cable from slipping out while reducing impacts and abrasion. 1 Pack contains 2 units.',
  features = '["Instant install: wraps around the lifeline in seconds, no tools required", "Soft protection: prevents impact and abrasion from stainless-steel cables", "Marine proof: UV and salt resistant for long-lasting performance", "Spiral-cut foam core for secure hold", "Compatible with sailboats of any size", "1 Pack contains 2 units"]'::jsonb,
  specifications = '{"Inner foam": "30 kg expanded polyethylene, spiral-cut", "Outer cover": "Sauleda fabric, UV & saltwater resistant", "Max guardrail diameter": "Ø 14 mm / 9/16 in", "Length": "1000 mm / 39.37 in", "Diameter": "40 mm / 1.57 in", "Total weight": "158 g / 0.34 lb", "Spiral pitch": "200 mm / 7.87 in", "Weight per unit": "25 g / 0.055 lb", "Pack contents": "2 units", "Compatible with": "Sailboats of any size", "Warranty": "4 years"}'::jsonb,
  technical_sheet_url = 'https://cdn.shopify.com/s/files/1/0244/3188/6432/files/scheda_tecninca_spira.pdf?v=1762965655',
  gallery_images = '["https://easysea.org/cdn/shop/files/GRAFICA-SPIRA-1.webp?v=1764689989&width=4500", "https://easysea.org/cdn/shop/files/EXP-02-Spira-GuardrailCover.webp?v=1764689989&width=4500", "https://easysea.org/cdn/shop/files/EXP-05-Spira-GuardrailCover.webp?v=1764689989&width=4500", "https://easysea.org/cdn/shop/files/EXP-03-Spira-GuardrailCover.webp?v=1764689989&width=4500", "https://easysea.org/cdn/shop/files/EXP-04-Spira-GuardrailCover.webp?v=1764689989&width=4500"]'::jsonb
WHERE product_family = 'spira';
